%% calculating the function and jacobi for self decided position data
% with adduction-abduction

% the variables for the angles, you differentiate for those!
syms mcp_I dip_I psi_I ...
     mcp_M dip_M psi_M ...
     mcp_R dip_R psi_R ...
     mcp_P dip_P psi_P;   

%% 4 magnets, 4 sensors
% b = varAngToBm_A_sym([mcp_I dip_I psi_I ...
%                       mcp_M dip_M psi_M ...
%                       mcp_R dip_R psi_R ...
%                       mcp_P dip_P psi_P], 4, 1);
                  
% jac = jacobian(b,[mcp_I dip_I psi_I ...
%                   mcp_M dip_M psi_M ...
%                   mcp_R dip_R psi_R ...
%                   mcp_P dip_P psi_P]);                  

%% one magnet, 4 sensors
b = varAngToBm_A_sym([mcp_I dip_I psi_I], 4, 1);

jac = jacobian(b,[mcp_I dip_I psi_I]);
                  
